name: blaze
channels:
  - bioconda
  - default
dependencies:
  - python=3.7
  - Biopython
  - pandas
  - numpy
  - tqdm
  - matplotlib
  - pip
  - pip:
    - levenshtein
    - fast-edit-distance
    - swifter
